### ISSUE TITLE
[MacOSX 10.10.1 / iTerm 2.1] Interaction problems

### ISSUE THREAD

**Issue by mjurczyk** [slap-editor/slap#164]
After release `slap@0.1.28` slap interaction does not automatically update (on click/on directional key).

Release 0.1.29 introduced some fix/feature (986b08177c4d79cf852cfd606831b731bc0fcd00?) that changed slap's behaviour under iTerm2 on Mac OS X.

Selection does not update unless user inputs text / selects another file. Mouse input and directional keys work and change selection, although it is not shown on the screen.

---

last working version:
```
slap@0.1.28, node@1.6.4, v8@4.1.0.27, openssl@1.0.1m, modules@43, ares@1.10.0-DEV, zlib@1.2.8, uv@1.4.2, http_parser@2.3.0
```

**Comment by dbkaplun** [comment]
@mjurczyk there is a race condition in NodeJS >0.10 and all versions of iojs that causes stdin to sporadically block on OSX (see libuv/libuv#304). This has been fixed as of libuv@1.6.0, which will be included in the next release of NodeJS (see joyent/node#25475).

Can you try installing under NodeJS 0.10 to confirm?

**Comment by rahsd** [comment]
with the latest nodejs from extra ppa for ubuntu I have the same issue.

**Comment by mjurczyk** [comment]
@dbkaplun sorry, but that doesn't seem to be a case.
Tried following configurations ( + previously on io.js ):

```
slap@0.1.31, node@0.11.16, v8@3.28.73, openssl@1.0.1l, modules@14, zlib@1.2.8, uv@1.0.2, http_parser@2.3
```

```
slap@0.1.31, node@0.10.38, v8@3.14.5.9, openssl@1.0.1m, modules@11, zlib@1.2.8, uv@0.10.36, ares@1.9.0-DEV, http_parser@1.0
```

Both work smoothly on slap@v0.1.28, none runs smoothly on any further version.

Under ***v0.9.12*** package could not be installed due to dependency errors:

```
.....
npm http GET https://registry.npmjs.org/bluebird
npm http 200 https://registry.npmjs.org/iconv-lite
npm ERR! Error: No compatible version found: iconv-lite@'^0.4.4'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.2.0","0.2.1","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.4.0-pre","0.4.0-pre2","0.4.0-pre3","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.4.5","0.4.6","0.4.7","0.4.8","0.4.9","0.4.10"]
npm ERR!     at installTargetsError (/.nvm/v0.9.12/lib/node_modules/npm/lib/cache.js:679:10)
npm ERR!     at /.nvm/v0.9.12/lib/node_modules/npm/lib/cache.js:594:10
npm ERR!     at saved (....)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.0.0
npm ERR! command "...."
npm ERR! node -v v0.9.12
npm ERR! npm -v 1.2.12
....
```

**Comment by dbkaplun** [comment]
I've pushed an `issue-164` branch that might fix your problems. Can you try `npm install -g slap-editor/slap#issue-164` and see if that solves your issue?

I am using iTerm 2.1 as well and cannot reproduce. If that doesn't help, can you try `npm install -g slap-editor/slap#<commit>` for each commit between 0.1.28 (known good) and 0.1.29 (known bad) so we can determine what commit is to blame?

**Comment by mjurczyk** [comment]
@dbkaplun unfortunately `issue-164` did not fix the issue. I will try finding the breaking commit.

**Comment by mjurczyk** [comment]
Just as I thought, https://github.com/slap-editor/slap/commit/986b08177c4d79cf852cfd606831b731bc0fcd00 breaks the interactions.

After checking things in the commits I found that `text-buffer` is the problem. Limiting `text-buffer` version to `6.1.x` fixes the problem on both node and iojs.

**Comment by dbkaplun** [comment]
I've released 0.1.32 with your PR. Can you confirm the issue is fixed?

**Comment by mjurczyk** [comment]
Version 0.1.32 works perfectly for me on iojs ;)

**Comment by dbkaplun** [comment]
Excellent, closing. :)
