### ISSUE TITLE
Moving mouse into/out of terminal prints garbage

### ISSUE THREAD

**Issue by acb** [slap-editor/slap#74]
OS: Ubuntu 12.04
Terminal: Default, Terminator, UXTerm, probably all

When Slap is open when I move my mouse into/out of the terminal window Slap inserts all sorts of crazy characters, such as '�J[MC�J�O[MC�O[MC�N'

Some notes on the circumstances:
I was SSH'd to a box that had slap on it, and used it there.
It ONLY happens when the terminal window is wider than 191 columns.

I understand that the problem in general is that the terminal is getting mouse events that aren't handled correctly, but hopefully you can find a way to mask them.

**Comment by wpg4665** [comment]
Same issue, using MobaXterm terminal. PLEASE help!! Love this editor, would like to actually start using and recommending, but the garbage on mousemove is killing it! Willing to help with any logs/more info as necessary

**Comment by secrettriangle** [comment]
@wpg4665 (or anyone else with this issue) would you have time for a screenshare session over Google Hangouts? Feel free to add me at dan@secrettriangle.net and we can schedule something over chat.

**Comment by wpg4665** [comment]
slap.log gist from screenshare with @secrettriangle 

https://gist.github.com/wpg4665/ec316db169deb150ec6b

**Comment by secrettriangle** [comment]
I'm able to reproduce this issue locally on MobaXTerm. It seems that terminal info is coming through incorrectly. We were able to get different behavior by passing a command-line parameter `slap --term=$TERM` where `$TERM` can be `vt100`, `vt101`, `vt102`, `vt220`, `vt240`, `vt320`, `vt330`, `vt340`, `vt420`, `vt510`, `vt520`, `vt525`, `linux`, `screen`, `xterm`, `rxvt`, and `rxvt-unicode`. Most of them (with the exception of `linux`) did not support the mouse at all. The `$TERM`s prefixed with `vt` ignored the mouse altogether, so garbage didn't come through, but other keybindings got messed up (e.g. pressing up and down caused slap to output `[B` and `[A`). Now that I have a reproducible environment I will be looking at this issue more closely.

**Comment by zlamalp** [comment]
Hi, i installed slap yesterday. I use xfce4-terminal on Xubuntu 14.04 LTS. Terminal app is set to xterm emulation. It prints garbage when I reach right side of application, but only when terminal window is wider than 190 columns.

Also probably related is, that help button in top right corner is clickable only when terminal window is smaller than 100 columns.

I didn't noticed any of this issues on my home computer yesterday (same os, settings etc.). I guess it's because it has smaller screen resolution (1024) opposite to full HD in work - leading to smaller number of terminal columns.

**Comment by chjj** [comment]
This will be fixed with the next release of blessed (tonight). Sorry for the inconvenience.

**Comment by secrettriangle** [comment]
I've updated to the most recent version of blessed. Can anyone confirm this has been fixed?

**Comment by fskreuz** [comment]
Still happening on my setup

Host:
Cygwin
mintty 1.2beta-1
Windows 8.1 64bit
Vagrant 1.6.5

Guest:
Ubuntu Precise 12.04 64bit
NodeJS v0.10.36

**Comment by chjj** [comment]
@fskreuz, are you positive you're using the latest blessed? I cannot reproduce this at all now. I could before.

**Comment by fskreuz** [comment]
@chjj I just cleaned the cache of my npm, uninstalled and reinstalled slap and it still happens. I'm not entirely sure if it's my setup though that's messing with me. Will try later on a PC running Ubuntu natively just to be sure.

**Comment by wpg4665** [comment]
Confirmed to still be having the issue as well on slap v.0.1.4

Is there a specific $TERM we should be using??

**Comment by chjj** [comment]
If I can't reproduce this on any terminal, I can't fix it. Please post your terminals, versions, whether you're using tmux/screen, $TERM values, node/io.js versions, and blessed versions.

I've tried to reproduce this now on several terminals, but the main issue here was the node.js key parser thinking mouse events were keys. Blessed no longer uses the node.js key parser and reverted to an older one. On top of that, it was modified to specifically filter out mouse events. I don't see how we could ever go to greater lengths to prevent this if it is still happening. Are you absolutely sure you're using the latest blessed?

```
$ cd /path/to/slap
$ grep version node_modules/blessed/package.json
$ npm ls blessed
```

Please tell me what the output of the above commands is. If you get something other than v0.0.45, clear your node_modules and do another npm install.

**Comment by fskreuz** [comment]
Slap installs with v0.0.45 of blessed (even when doing `npm install` in slap). Manually installing blessed takes it to v0.0.47 (the latest on Github) and then... still happening.

Host:
Cygwin
mintty 1.2beta-1
Windows 8.1 64bit
Vagrant 1.6.5

Guest (where slap is installed)
Ubuntu Precise 12.04 64bit
NodeJS v0.10.36
no tmux
Blessed 0.0.47
xterm-256color

**Comment by chjj** [comment]
You guys will have to be my eyes here since I can't reproduce this. Could you try the latest commit to blessed? https://github.com/chjj/blessed/commit/a33525750528a392d5217aca427313f08a1038f7

**Comment by chjj** [comment]
Also, @fskreuz, what do you mean when you say cygwin? You're running a vm of ubuntu in mintty similar to qemu's vga->curses capability? Or you have Ubuntu running and you're simply ssh'ing into it from your cygwin terminal? Or is that irrelevant and you actually have a display server running on you Ubuntu vm? If so, what terminal are you running on Ubuntu (not your $TERM, the actual terminal).

**Comment by secrettriangle** [comment]
@wpg4665 what OS are you using? On Linux, I use it with GNOME Terminal, and on OSX, I use iTerm2, both of which work great.

@chjj I was able to reproduce consistently on MobaXTerm... See [#issuecomment-68796541](#issuecomment-68796541)

**Comment by fskreuz** [comment]
@chjj Tested on a Lubuntu and it works fine there.

**Lubuntu**:
- OS: Lubuntu 14.04.1 LTS
- Terminal: LXTerminal 0.1.11
- $TERM: "xterm"
- NodeJS: 0.10.36
- NPM: 1.4.28
- Blessed: 0.0.45
- no tmux

As for the VM question, the VM is a headless VM. I ssh to the VM via Cygwin. Already switched the `$TERM` for Cygwin to `xterm` (from `xterm-256color`) and still the same result. Must be the Cygwin.

**Comment by chjj** [comment]
So this only affects windows terminals? Does Putty produce the same results?

**Comment by fskreuz** [comment]
@chjj Just tested Putty. Didn't happen there.

**Comment by chjj** [comment]
Strange considering mobaxterm is based on putty. I guess I'll have to fire up the old windows vm.

**Comment by chjj** [comment]
I suspect cygwin and mobaxterm are sending mouse events in chunks. That's the only thing that would explain this, which means we need a state machine to parse all keys and mouse events. Not very convenient. This is just a hunch, but it seems like the explanation.

**Comment by wpg4665** [comment]
Wow, so I just updated to Mobaxterm Pro v7.5...$TERM = xterm. Absolutely no issues!! =D

**Comment by chjj** [comment]
Can't reproduce with cygwin 1.7.34.

**Comment by chjj** [comment]
Oh, I didn't notice you were using mintty. I'll try that.

**Comment by chjj** [comment]
mintty works fine too.

**Comment by secrettriangle** [comment]
If nobody else has issues, I'm going to mark this closed. Thanks @chjj!

**Comment by wpg4665** [comment]
That sounds perfectly acceptable! Thank you for the work you put in to
fixing this! =D

**Comment by fskreuz** [comment]
The latest seems to work already on my setup. :+1:
